server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway-service
          uri: https://github.com/is-lgarcia/microservices-example
          search-paths: config-data
  application:
    name: config-service